hyperledger-iroha/iroha-2-docs

- src/guide/bash.md
Added a small section TUI/CLI distinction and what users should expect. 
Signed-off-by: Aleksandr <a-p-petrosyan@yandex.ru>
> [documentation]: Add CLI/TUI expansion

- src/guide/bash.md
Signed-off-by: Aleksandr <a-p-petrosyan@yandex.ru>
> [fix]: Duplication.

- .vitepress/config.ts
- README.md
- src/guide/appendix/keys.md
- src/guide/build-and-install.md
- src/guide/conclusions.md
> docs: chores, update sidebar

- src/guide/build-and-install.md
> Fix appendix dead link

- src/guide/advanced/intro.md
- src/guide/bash.md
- src/guide/build-and-install.md
- src/guide/conclusions.md
- src/guide/javascript.md
- src/guide/kotlin-java.md
- src/guide/python.md
- src/guide/rust.md
Signed-off-by: William Richter <richter@soramitsu.co.jp>
> More advanced grammar fixes.

- src/guide/advanced/intro.md
@appetrosyan I fixed your previous comments and opened a PR from my fork
> improve documentation on wasm

- package.json
- pnpm-lock.yaml
- src/guide/javascript.md
Waiting for merging of https://github.com/hyperledger/iroha-javascript/pull/94
> Update JS guide according to RC3 version

- src/guide/advanced/queries.md
Signed-off-by: Aleksandr Petrosyan <a-p-petrosyan@yandex.ru>
Added info about queries added in RC4.
> [queries]: Added information about queries that were added in rc4.

- .github/CODEOWNERS
Added the list of codeowners. Addresses #47
> [chore] #47: Add codeowners

- src/guide/build-and-install.md
- src/guide/rust.md
- src/index.md
Signed-off-by: Aleksandr Petrosyan <a-p-petrosyan@yandex.ru>
> [reword]: Simplify and remove unclear clarifications and old info

- src/guide/rust.md
> [documentation] #53: Update syntax for RegisterBox

- README.md
Updated the readme a bit. View output: https://github.com/outoftardis/iroha-2-docs/tree/doc-readme#hyperledger-iroha-2-tutorial
> [documentation]: Update README

- src/guide/advanced/isi.md
- src/guide/advanced/wasm.md
- src/index.md
Reviewed topics on ISI and WASM, addressing #43
> [documentation]: Review ISI and WASM topics

- src/guide/configure/client-configuration.md
- src/guide/configure/peer-configuration.md
Reviewed two more topics, addressing #43
> [documentation]: Review peer and client configurations

- src/guide/advanced/triggers.md
- src/guide/configure/keys.md
> [documentation]: Review the Triggers chapter

- src/guide/advanced/queries.md
> [documentation]: Review the Queries chapter

- src/guide/iroha-2.md
> [documentation]: Review the Iroha 2 vs. Iroha 1 chapter

- src/guide/build-and-install.md
> [documentation]: Review Installation chapter

- .github/workflows/gh-pages-deploy.yaml
- .github/workflows/pull-request-format.yaml
> [CI]: target `main` branch in GitHub workflows

- src/guide/javascript.md
> [docs]: update version note in js guide

- src/guide/advanced/queries.md
To be merged after https://github.com/hyperledger/iroha/pull/2418
> Add FindTriggersByDomainId query

- src/guide/javascript.md
After discussing JS connection with Dmitry, I feel like the examples need to be updated.
> [docs] Update JS examples

- src/guide/advanced/queries.md
Addresses #79.
I am not sure if we should merge this before we figure out the versioning strategy (#89) for the tutorial.
> [docs] #79: Add block queries

- src/guide/javascript.md
When working through the tutorial I've found some issues with code samples, I'm sharing updates that should work with recent iroha2. `roses#wonderland` are no longer mintable for alice (since she didn't create them, I think I saw some issue regarding this on the main repo), so I've changed it to `time` with a note that proper mintable type must be set.
> [docs] update JS code samples

- src/guide/bash.md
I'd like to add a note on `kagami` tool to the account registration description.
Related issue: https://github.com/hyperledger/iroha-2-docs/issues/82
> [docs] Add a Kagami note

- src/guide/rust.md
> Update code snippet in Rust guide

- .github/CODEOWNERS
> Add Victor as a codeowner

- src/guide/iroha-2.md
> [docs] #97: Add a note about compatibility of Iroha v1/v2

- src/guide/advanced/queries.md
> [docs] #107: Add FindAllPermissionTokenDefinitions query

- src/guide/advanced/queries.md
- src/guide/advanced/triggers.md
> [docs] #105: Add a section on domain-scoped triggers

- src/guide/build-and-install.md
> [docs] #116: Add openssl installation instructions

- src/guide/javascript.md
> [docs] #120: Update JS installation instruction

- src/guide/build-and-install.md
> [docs]: Update install instructions

- src/guide/javascript.md
> [docs]: Update JS install

- src/guide/javascript.md
> [docs] #129: Add a note about iroha-javascript repo

- src/guide/python.md
> [docs] #127: Fix git clone in Python guide

- .vitepress/config.ts
- src/guide/advanced/isi.md
- src/guide/advanced/metadata.md
- src/guide/advanced/permissions.md
- src/guide/advanced/queries.md
- src/guide/advanced/wasm.md
- src/guide/build-and-install.md
- src/guide/rust.md
- src/index.md
Addresses #98, #108, #86 (without examples) + fixes formatting
> [docs]: Add info about metadata and sorting

- src/guide/python.md
> [docs] #144: Fix Python script

- src/guide/bash.md
> [fix]: Fix typo in Bash guide

- src/guide/advanced/permissions.md
- src/guide/advanced/queries.md
- src/guide/advanced/triggers.md
- src/guide/objects/hierarchy.md
- src/index.md
> [docs] #111: Add info about permission validators

- src/guide/advanced/isi.md
- src/guide/objects/hierarchy.md
> [docs] #160: Update links

- src/guide/configure/peer-configuration.md
Based on https://github.com/hyperledger/iroha/pull/2701
> [docs]: Change default BLOCK_STORE_PATH location

- src/guide/advanced/isi.md
> [fix]: Fix a typo

- src/guide/advanced/ffi.md
Added suggestion from Aleksandr: https://github.com/hyperledger/iroha-2-docs/pull/114#pullrequestreview-1079993948
> [docs]: Update FFI chapter

- src/guide/build-and-install.md
> [docs] #166: Add the location of build artifacts

- src/guide/javascript.md
> [docs]: remove obsolete comment

- src/guide/bash.md
> [docs]: Add a link to the test network

- src/guide/advanced/wasm.md
> [docs] #162: Update Wasm chapter

- src/guide/configure/client-configuration.md
> [docs] #170: Update client config page

- src/guide/python.md
Signed-off-by: Artemii Gerasimovich <gerasimovich@soramitsu.co.jp>
- Fixed snippets in python section of the guide
> [fix] #146: update snippets in python section

- src/guide/bash.md
> [docs] #81: Add example on transferring assets to Bash guide

- src/guide/build-and-install.md
Small optimize the number of steps on the build and install page #197
Signed-off-by: astrokov7 <111361420+astrokov7@users.noreply.github.com>
> [docs] #197: Optimize the number of steps on the build and install page

- src/guide/configure/peer-configuration.md
> [docs] #182: Update peer config page

- .vitepress/config.ts
- src/api/index.md
- src/guide/advanced/hot-reload.md
- src/guide/advanced/metrics.md
- src/guide/configure/genesis.md
- src/guide/configure/keys.md
- src/guide/glossary.md
- move some docs from iroha repository (see pr: https://github.com/hyperledger/iroha/pull/2879)
- update the chapter on genesis (partially addresses #171)
> [docs]: Move files from main repo

- .vitepress/config.ts
- src/guide/advanced/isi.md
- src/guide/bash.md
- src/guide/configure/modes.md
- src/guide/objects/assets.md
- src/guide/rust.md
> [docs] #193: Update instructions page, add a page on modes

- src/guide/advanced/ffi.md
@outoftardis go ahead and take over this PR
Signed-off-by: Marin Veršić <marin.versic101@gmail.com>
> FFI doc update

- src/guide/kotlin-java.md
Updates the Kotlin configuration according to Bogdan's suggestion.
We're not using the private repos this way.
> Redefine a Kotlin configuration

- src/guide/bash.md
> [docs] #216: Add client_cli subcommands

- src/guide/bash.md
> [docs] #221: Add json subcommand

- src/guide/advanced/queries.md
> [docs] #215: Update asset queries

- src/guide/kotlin-java.md
The example is taken from here: https://github.com/hyperledger/iroha-java/blob/iroha2-dev/modules/client/src/test/java/jp/co/soramitsu/iroha2/JavaTest.java
Closes #227
> [docs] #227: Update pure Java example

- src/guide/bash.md
> [docs] #226: Update `permission_token.json` example

- src/example_code/lorem.rs
Signed-off-by: Dmitry Balashov <a.marcius26@gmail.com>
By the way, **there is a known issue:** 
I've opened a PR to fix it, but it hasn't been merged yet:
- https://github.com/vuejs/vitepress/pull/1687
> [fix]: sample region in `lorem.rs`

- src/guide/iroha-2.md
- src/index.md
Addresses https://github.com/hyperledger/iroha/issues/2579
> [docs] #2579: Link to Iroha 1 documentation

- src/guide/configure/client-configuration.md
- src/guide/configure/peer-configuration.md
> [docs] #237: Add instructions on kagami config generation

- src/documenting/code-groups.md
- src/guide/glossary.md
- src/guide/iroha-2.md
- src/guide/rust.md
- src/guide/troubleshooting/configuration-issues.md
- src/index.md
- Moved troubleshooting info from the rust guide to the troubleshooting section
- Fixed formatting
> [docs]: Update troubleshooting section, fix formatting

- src/guide/advanced/hot-reload.md
- src/guide/advanced/metrics.md
- src/guide/advanced/running-iroha-on-bare-metal.md
- src/guide/blockchain/wasm.md
- src/guide/build.md
- src/guide/configure/client-configuration.md
- src/guide/configure/genesis.md
- src/guide/configure/peer-configuration.md
- src/guide/install.md
- src/guide/javascript.md
- src/guide/python.md
- src/guide/quick-start.md
- src/guide/rust.md
- src/guide/troubleshooting/installation-issues.md
> [docs] #267: Update sh-lang code blocks

- .vitepress/config.ts
> [fix] #143: update Algolia api key

- .env
> [chore]: change feedback form url (#284)

- etc/meta.ts
- src/guide/javascript.md
> [docs] #313: update JS reference to `rc13`

- src/guide/python.md
After discussing the Python SDK versioning with @QuentinI, I think we should update the SDK doc.
> [chore] Update Python SDK version warning

- .vitepress/config.ts
- src/guide/reports/csd-rtgs.md
Added a stub article with almost empty contents to provide link to Matthias.
> [feature]: add CSD-RTGS stub for link to Matthias

- .vitepress/config.ts
- src/guide/configure/metadata-and-store-assets.md
Part of https://github.com/hyperledger/iroha-2-docs/issues/308
> Metadata and store assets

- src/guide/troubleshooting/installation-issues.md
I am unsure of many details to put into the distribution and shell path updates, so I'll leave it as a draft. I am thinking about Ubuntu, Arch, and maybe some RedHat distros. As for the shells: Fish, Bash, and ZSH should be enough. Any ideas?
> Pip update for wheel issue #320

- src/guide/bash.md
Added account switching and resolved permission token collision in transfering assets to resolve this issue https://github.com/hyperledger/iroha-2-docs/issues/291
> Added account switching and resolved permission token collision in transfering assets

- MAINTAINERS.md
Closes https://github.com/hyperledger/iroha-2-docs/issues/381
> [chore]: #381 add @yamkovoy to the MAINTAINERS.md

- src/guide/blockchain/queries.md
> #354: Fix output value

- src/guide/configure/client-configuration.md
Closes https://github.com/hyperledger/iroha-2-docs/issues/395
> #395: Explain the use of BASIC_AUTH in the docs

- src/guide/glossary.md
> #399: Add the definition of a peer to the glossary page

- .vitepress/config.ts
- package.json
- pnpm-lock.yaml
- src/guide/blockchain/instructions.md
> [feature]: support TeX math with KaTeX

- src/guide/blockchain/filters.md
- src/guide/blockchain/metadata.md
- src/guide/blockchain/permissions.md
- src/guide/blockchain/queries.md
> #406: Remove as Identifiable from examples

- .vitepress/theme/components/CompatibilityMatrixTableIcon.vue
- .vitepress/theme/style/index.scss
- src/reference/compatibility-matrix.md
> Stylistic chores

- src/guide/blockchain/transactions.md
> [docs] #437: Mention rejected transactions
