hyperledger-iroha/iroha-2-docs

- src/guide/build-and-install.md
- src/guide/python.md
While working on https://github.com/hyperledger/iroha/issues/1466, I've noted a "docker compose command". I don't think [Compose](https://docs.docker.com/compose/) is a part of default Docker distribution.
If I will try to run it with just `docker` command, I'll see this:
```bash
$ docker compose up
docker: 'compose' is not a docker command.
See 'docker --help'
```
Versions:
```
Docker version 20.10.16, build aa7e414fdc
docker-compose version 1.29.2, build 5becea4c
```
> Fix docker-compose command

- src/guide/advanced/triggers.md
This is meant to address #59. We need to add info on domain-scoped triggers (#105) but it seems that it will only be possible to do after the versioning is in place (#89), otherwise we'll mix versions.
Closes #59.
> [docs] #59: Update statements about triggers

- .github/workflows/pull-request-ci.yaml
Now we will be able to inspect build errors in GitHub instead of Vercel.
> [ci]: run `build` in PR CI as well

- src/guide/python.md
Previously, a `cd` command was missing and a change was requested by @learningnoobi.
> [docs] Add a missing cd command

- src/guide/configure/genesis.md
- src/guide/iroha-2.md
- src/index.md
I would like to add some new links, because it may be convenient for the new users.
* `iroha_client_cli` - link to "how Iroha works"
* "Use efficient portable smart contracts implemented either via WebAssembly" - link to WASM
* "Bash, Rust, Kotlin, Javascript, or Python" - language guides
* "Iroha 2 vs. Iroha 1" → "Fault Tolerance" - link to the Sumeragi whitepaper
This PR also contains some cosmetic changes: uniform links in the index file and a whitespace change in a command.
> [docs] Update links #239

- src/guide/troubleshooting/configuration-issues.md
I've just added a tutorial config troubleshooting section related to the issue we've encountered with @astrokov7, the outdated genesis when using Docker.
Before this PR is merged, I'd like to understand how we address a practical situation when the genesis file is outdated but there's data already.
* May Iroha break that way?
* Do we have a mechanism to backup and restore the data?
* If not, should we use other peers as a method to backup data?
> [docs] Add genesis troubleshooting #241

- src/guide/glossary.md
- src/index.md
A small extension for the glossary, so the doc is easier to navigate without confusing the user with the terminology.
It is possible to link the assets instead of the glossary for the asset-related part, but I believe the glossary section should be separate.
> [docs] Extend the glossary

- .vitepress/config.ts
- src/guide/support.md
As mentioned in #249, I'd like to add the support channels in the documentation, so the users can contact us more quickly.
Closes #249 
> [docs] #249: Add the support channels

- .vitepress/config.ts
- etc/cli.ts
- etc/snippet_sources.ts
- etc/types.ts
- etc/util.spec.ts
- etc/util.ts
- src/api/index.md
> [feature] #286: link `api_spec` from the core repo

- src/guide/bash.md
People can start with the Bash guide; however small this change is, it may help reduce confusion.
Closes #289
> [chore] #289: add iroha_client_cli build link

- etc/snippet_sources.ts
There was a typo in path which led to 404:
> [chore]: fix typo in path to `api_spec` on GitHub

- src/guide/rust.md
As stated in https://github.com/hyperledger/iroha-2-docs/issues/295, we should add a link to the XDG specification if someone needs to get acquainted with it.
---
Moreover, a footnote telling which variable in the spec would be helpful. For example, we can write that `iroha_client_cli` will look for `$XDG_CONFIG_HOME`.
Iroha doesn't start on my machine right now, while digging in the source shows [this code](https://github.com/hyperledger/iroha/blob/726f5eabf65a79ea618b4fce62a09cee7a5b13d1/client_cli/src/main.rs#L141-L142).
So far, I've tried this code to see that it shows a subdirectory relative to the current working dir.
```rust
#![allow(unused)]
#![feature(absolute_path)]
#[cfg(unix)]
fn main() -> std::io::Result<()> {
use std::path::{self, Path};
let absolute = …
```
> [chore] #295: add XDG specification link

- .vitepress/config.ts
This commit adds [Google Analytics](https://analytics.google.com) user activity tracking into Iroha tutorial.
This was requested on standup and would allow to understand what pages users are looking for.
> [chore]: Add Google Analytics

- src/guide/bash.md
- src/guide/python.md
- src/guide/rust.md
`cp ./configs/client_cli/config.json test_docker/` command won't work anymore; `cp ./configs/client/config.json test_docker/` would work in `iroha2-dev`, `dae3113496`.
I wonder if we need to do something about the Java and JavaScript articles, as `config.json` is mentioned there briefly, but Bash is the first thing to try. I think I will update those as well.
> [chore] Fix client config path (#358)

- src/guide/blockchain/triggers.md
- Change `tip` to `warning`
- Align the warning with the list item about `Burn`, not the whole list
> [chore]: update `Burn<Trigger, u32>` warning

- src/api/torii-endpoints.md
See:
- https://github.com/hyperledger/iroha/pull/3983
> [docs]: update `GET /status` reference

- src/api/torii-endpoints.md
After the merge of https://github.com/hyperledger/iroha/pull/4016 a new query parameter will be added.
This PR adds this info to the documentation
> Add `fetch_size` query parameter to torii-endpoints.md

- .vitepress/config.mts
- src/guide/security/generating-cryptographic-keys.md
- The **Storing Cryptographic Keys** topic was inaccessible for users due to `.vitepress/config.mts` containing a typo, which resulted in both the **Generating Cryptographic Keys** and **Storing Cryptographic Keys** buttons of the navbar leading to the **Generating Cryptographic Keys** topic.
- A case of bad VitePress-related syntax, which resulted in the hosted HTML page containing an unformatted custom container.
> Security: Navigation and bad syntax bug fix

- src/reference/torii-endpoints.md
Follow-up of this PR:
- ~~https://github.com/hyperledger/iroha/pull/4076~~  https://github.com/hyperledger/iroha/pull/4100
> [docs]: update configuration endpoints

- src/guide/blockchain/instructions.md
- src/guide/blockchain/metadata.md
- src/reference/permissions.md
Refactored the permissions example
> Permission token examples

- src/guide/advanced/metrics.md
- src/guide/advanced/running-iroha-on-bare-metal.md
- src/guide/configure/configuration-types.md
- src/guide/configure/peer-configuration.md
- src/guide/configure/sample-configuration.md
- src/reference/torii-endpoints.md
- Updated and polished the **Torii Endpoints** topic:
- Added intro;
- Streamlined the structure of the entries (operations);
- Clarified wording;
- Added context and cross-references, etc;
- Added responses;
- Added several **TODO** reminders for future updates.
- Fixed and/or removed dead links in the related topics (e.g., **Advanced** > **Metrics**).
> Updated and polished the "Torii Endpoints" topic

- etc/meta.ts
- etc/schema/render.ts
- etc/schema/types.ts
- etc/snippet-sources.ts
- src/guide/configure/client-configuration.md
- src/guide/configure/peer-configuration.md
- src/guide/configure/sample-configuration.md
- src/reference/torii-endpoints.md
This PR does three things:
- support for bitmaps in schema (introduced in https://github.com/hyperledger/iroha/pull/4381)
- "fixes" paths to referenced config files
- updates torii reference to be in line with https://github.com/hyperledger/iroha/pull/4544
While the inclusion of toml templates in place of old json files makes the config documentation "wrong", this allows writing new documentation with references to a more up-to-date `schema.json`.
In the end I think the #397 will in the end remove the toml templates altogether, I consider this just a way to unblock my updates to the torii reference for https://github.com/hyperledger/iroha/pull/4544
@0x009922 Do you think it's a good approach? Or should we try somehow to keep the old `json`'s in place while the new config reference is not …
> Update the data model reference to the latest iroha dev revision

- src/guide/advanced/running-iroha-on-bare-metal.md
- src/guide/get-started/python.md
- src/guide/get-started/quick-start.md
> Replace `docker-compose` (V1) with `docker compose` (V2)

- src/guide/get-started/install-iroha-2.md
`iroha_client_cli` and `kagami` were renamed in https://github.com/hyperledger/iroha/pull/4970
> Rename crates iroha_cli and iroha_kagami

- .vitepress/config.mts
- README.md
- etc/meta.ts
- etc/schema/types.ts
- etc/snippet-sources.ts
- src/blockchain/consensus.md
- src/blockchain/instructions.md
- src/blockchain/triggers.md
- src/blockchain/wasm.md
- src/documenting/snippets.md
- src/get-started/index.md
- src/get-started/install-iroha-2.md
- src/get-started/iroha-2.md
- src/get-started/launch-iroha-2.md
- src/guide/advanced/metrics.md
- src/guide/advanced/running-iroha-on-bare-metal.md
- src/guide/configure/configuration-types.md
- src/guide/configure/keys-for-network-deployment.md
- src/guide/configure/peer-configuration.md
- src/guide/configure/peer-management.md
- src/guide/configure/sample-configuration.md
- src/guide/tutorials/javascript.md
- src/guide/tutorials/kotlin-java.md
- src/guide/tutorials/python.md
- src/guide/tutorials/rust.md
- src/help/index.md
- src/index.md
- src/reference/torii-endpoints.md
Iroha repositories were migrated from `hyperledger` organization  to `hyperledger-iroha`. This updates the links in the docs.
> link fixes due to migration

- .github/workflows/pull-request-ci.yaml
- .vitepress/theme/index.ts
- etc/meta.ts
- etc/schema/render.ts
- etc/snippet-sources.ts
- src/reference/torii-endpoints.md
- Removed "pending transactions" endpoint
- Added Telemetry > Peers endpoint
- Grouped telemetry endpoints, renamed to "Telemetry / ..."
- Added feature badges (without explanations though) to indicate which Iroha compile features enable certain endpoints.
> docs: update torii reference to reflect `rc.1`

- etc/meta.ts
- etc/snippet-sources.ts
- src/guide/advanced/metrics.md
- src/reference/torii-endpoints.md
- Reflect https://github.com/hyperledger-iroha/iroha/pull/5380
- Update some other irrelevant information
Closes #519
> docs: update status/metrics/peers endpoints + reference `rc.2.0`
